### ISSUE TITLE
Technique for adding the current user

### ISSUE THREAD

**Issue by kkinder** [encode/sentry-asgi#11]
sentry-asgi does not seem to have a way of setting the current user. Regular sentry seems to recommend this:

```
from sentry_sdk import configure_scope

with configure_scope() as scope:
    scope.user = {"email": "john.doe@example.com"}
```

But that seems to run immediately with sentry-asgi, so I'm not sure how to add the currently authenticated user. Recommendations?

**Comment by lovelydinosaur** [comment]
> But that seems to run immediately with sentry-asgi

How do you mean "seems to run immediately"?

**Comment by lovelydinosaur** [comment]
(Linking to https://docs.sentry.io/development/sdk-dev/interfaces/user/ for my own later reference)

**Comment by kkinder** [comment]
> How do you mean "seems to run immediately"?

Here's an example:

```import sentry_sdk
import uvicorn
from sentry_asgi import SentryMiddleware
from sentry_sdk import configure_scope
from starlette.applications import Starlette
from starlette.responses import JSONResponse

app = Starlette()

with configure_scope() as scope:
    print('CONFIGURE SCOPE')
    scope.user = {"email": "john.doe@example.com"}

sentry_sdk.init("...")
app.add_middleware(SentryMiddleware)

@app.route('/')
async def homepage(request):
    return JSONResponse({'hello': 'world'})

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)
```

If you run that "CONFIGURE SCOPE" is printed once, as the app starts up, not on each request as you would expect:

```
$ python foo.py
CONFIGURE SCOPE
INFO: Started server process [24384]
INFO: Waiting for application startup.
INFO: Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO: ('127.0.0.1', 59338) - "GET / HTTP/1.1" 200
INFO: ('127.0.0.1', 59338) - "GET / HTTP/1.1" 200
INFO: ('127.0.0.1', 59338) - "GET / HTTP/1.1" 200
INFO: ('127.0.0.1', 59338) - "GET / HTTP/1.1" 200
```

See that CONFIGURE SCOPE? It should be called for each request, presumably because each request could come from a different user, different IP, etc. Unless I'm misunderstanding something?

**Comment by meadsteve** [comment]
I believe I have a solution for this in #14 . That PR adds the sentry_hub to the request scope. So that any additional middleware or handler can update the scope with the user:
```python
sentry_hub: Hub = request.get("sentry_hub")
    if sentry_hub:
        with sentry_hub.configure_scope() as scope:
            scope.user = {"id": request.user.id}
```
In my code base I have an extra middleware that runs after the sentry and auth ones to set this scope.

**Comment by lovelydinosaur** [comment]
Closing all issues off and archiving this repo, now that we're deferring to Sentry's built-in ASGI support.
