### ISSUE TITLE
consider "x-forwarded-for" header for client remote IP

### ISSUE THREAD

**Issue by backbohne** [encode/sentry-asgi#15]
Could not find a other solution, but it could be implemented like below (`SentryMiddleware.event_processor`):

```python
    ...
    event["request"]["env"] = {
        "REMOTE_ADDR": self.get_headers(asgi_scope).get(
            'x-forwarded-for', 
            asgi_scope["client"][0]
        )
    }
    ...
```

**Comment by lovelydinosaur** [comment]
I'd suggest dealing with this in ASGI middleware.

Uvicorn has various configuration allowing the remote IP to be properly configured depending on the proxy/gateway setup that the host is running behind. (Although it could do a better job at following gunicorn's lead and deferal to appropriate environment variables here)
