### ISSUE TITLE
Lifespan issue with django channels 

### ISSUE THREAD

**Issue by ferndot** [encode/sentry-asgi#8]
When using sentry-asgi with uvicorn and Django Channels, I get this error: `ValueError: No application configured for scope type 'lifespan'`. This issue does not occur without sentry-asgi.

A similar issue was addressed here:
https://github.com/encode/uvicorn/issues/222

**Comment by lovelydinosaur** [comment]
Closing all issues off and archiving this repo, now that we're deferring to Sentry's built-in ASGI support.
